version: '2'
services:

    blink-python:
        build:
            context: python/blink/
            dockerfile: Dockerfile
        image: 'chimpwizard/pi-blink:python'
        devices: 
            - /dev/gpiomem
        volumes:
             - "/var/run/docker.sock:/var/run/docker.sock"

    button-python:
        build:
            context: python/button/
            dockerfile: Dockerfile
        image: 'chimpwizard/pi-button:python'
        devices: 
            - /dev/gpiomem
        volumes:
             - "/var/run/docker.sock:/var/run/docker.sock"

    node:
        build:
            context: node/blink
            dockerfile: Dockerfile
        image: 'chimpwizard/pi-blink:node'
        devices: 
            - /dev/gpiomem
        entrypoint: sh
        volumes:
             - "/var/run/docker.sock:/var/run/docker.sock"
             - "/sys/class/gpio/export:/sys/class/gpio/export"
             - "/sys/devices/platform/soc/20200000.gpio/gpiochip0:/sys/devices/platform/soc/20200000.gpio/gpiochip0"

    blink-node:
        build:
            context: node/blink
            dockerfile: Dockerfile
        image: 'chimpwizard/pi-blink:node'
        devices: 
            - /dev/gpiomem
        volumes:
             - "/var/run/docker.sock:/var/run/docker.sock"
             - "/sys/class/gpio/export:/sys/class/gpio/export"
             - "/sys/devices/platform/soc/20200000.gpio/gpiochip0:/sys/devices/platform/soc/20200000.gpio/gpiochip0"

    button-node:
        build:
            context: node/button
            dockerfile: Dockerfile
        image: 'chimpwizard/pi-button:node'
        devices: 
            - /dev/gpiomem
        volumes:
             - "/var/run/docker.sock:/var/run/docker.sock"
             - "/sys/class/gpio/export:/sys/class/gpio/export"
             - "/sys/devices/platform/soc/20200000.gpio/gpiochip0:/sys/devices/platform/soc/20200000.gpio/gpiochip0"

    helloworld:
        build:
            context: node/helloworld
            dockerfile: Dockerfile
        image: 'chimpwizard/pi-helloworld:node'
        devices: 
            - /dev/gpiomem
        ports:
            - 8000:8000
        volumes:
             - "/var/run/docker.sock:/var/run/docker.sock"
             - "/sys/class/gpio/export:/sys/class/gpio/export"
             - "/sys/devices/platform/soc/20200000.gpio/gpiochip0:/sys/devices/platform/soc/20200000.gpio/gpiochip0"

    dashboard:
        build:
            context: node/dashboard
            dockerfile: Dockerfile
        image: 'chimpwizard/pi-dashboard:node'
        devices: 
            - /dev/gpiomem
        ports:
            - 8000:8000
        volumes:
             - "/var/run/docker.sock:/var/run/docker.sock"
             - "/sys/class/gpio/export:/sys/class/gpio/export"
             - "/sys/devices/platform/soc/20200000.gpio/gpiochip0:/sys/devices/platform/soc/20200000.gpio/gpiochip0"
    red:
        build:
            context: node/red
            dockerfile: Dockerfile
        image: 'chimpwizard/pi-red:node'
        # devices: 
        #     - /dev/gpiomem
        #entrypoint: bash
        ports:
            - 1880:1880
        volumes:
             - ./node/red/data/flows.json:/data/flows.json #Comment this for development purposes. Uncommend when deploying on the Pi
             - "/var/run/docker.sock:/var/run/docker.sock"
             #- "/sys/class/gpio/export:/sys/class/gpio/export"
             #- "/sys/devices/platform/soc/20200000.gpio/gpiochip0:/sys/devices/platform/soc/20200000.gpio/gpiochip0"