version: '2'
services:

    blink:
        build:
            context: python/blink/
            dockerfile: Dockerfile
        image: 'chimpwizard/pi-blink:python'
        volumes:
             - "/var/run/docker.sock:/var/run/docker.sock"

    button:
        build:
            context: python/button/
            dockerfile: Dockerfile
        image: 'chimpwizard/pi-button:python'
        volumes:
             - "/var/run/docker.sock:/var/run/docker.sock"

    blink-node:
        build:
            context: node/blink
            dockerfile: Dockerfile
        image: 'chimpwizard/pi-blink:node'
        volumes:
             - "/var/run/docker.sock:/var/run/docker.sock"

    button-node:
        build:
            context: node/button
            dockerfile: Dockerfile
        image: 'chimpwizard/pi-button:node'
        volumes:
             - "/var/run/docker.sock:/var/run/docker.sock"