version: '3'
services:

    python:
        build:
            context: python/
            dockerfile: Dockerfile
        image: 'chimpwizard/pi:python'
        volumes:
             - "/var/run/docker.sock:/var/run/docker.sock"

    node:
        build:
            context: node/
            dockerfile: Dockerfile
        image: 'chimpwizard/pi:node'
        volumes:
             - "/var/run/docker.sock:/var/run/docker.sock"
