version: "3.2"

networks:
  kafka:

services:

  kafka:
    image: spotify/kafka
    environment:
      - ADVERTISED_HOST=172.10.10.20
      - ADVERTISED_PORT=9092
    networks:
      - kafka
    ports:
      - 2181:2181
      - 9092:9092
