version: '3'
services:
  console:
      image: portainer/portainer
      volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
      ports:
          - '9000:9000'
      networks:
          - helloworld
      command: "-H tcp://172.10.10.20:4243 --admin-password '$$2y$$05$$/SVcW3.dRcqFP61JCNgj9.L0BnTre7OnOL3E3dSHIUX0uKLp5aR/e'"

networks:
  helloworld:
    external: false
