---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: healthz
  name: healthz
  namespace: ns-xyz
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
    nodePort: 30911
  selector:
    app: healthz
---

