version: "3.0"
networks:
  dgraph:

services:

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - dgraph


  zero:
    build:
      context: .
      dockerfile: Dockerfile

    image: chimpwizard/dgraph:latest
    environment:
      - 'TASK_SLOT={{.Task.Slot}}'
    networks:
      - dgraph
    deploy:
      replicas: 3
    command: --command zero --my $$HOSTNAME:508$$TASK_SLOT --replicas 3 --idx $$TASK_SLOT  -o $$TASK_SLOT --peer zero:5081  -v 2


  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: chimpwizard/dgraph:latest
    ports:
      - 8080:8080
      - 9080:9080
    environment:
      - 'SOMENAME1={{.Service.ID}}'
      - 'SOMENAME2={{.Service.Name}}'
      - 'SOMENAME3={{.Service.Labels}}'
      - 'SOMENAME4={{.Node.ID}}'
      - 'SOMENAME5={{.Task.ID}}'
      - 'SOMENAME6={{.Task.Name}}'
      - 'TASK_SLOT={{.Task.Slot}}'
    networks:
      - dgraph
    deploy:
      replicas: 3
    command: --command server --my $$HOSTNAME:7080 --lru_mb 2048 --zero zero:5081  -v 2

  ratel:
    image: dgraph/dgraph:latest
    ports:
      - 8000:8000
    networks:
      - dgraph
    command: dgraph-ratel

  console:
      image: portainer/portainer
      volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
      ports:
          - '9000:9000'
      networks:
          - dgraph
      # deploy portainer using default password as "password"
      command: "-H tcp://172.10.10.20:4243 --admin-password '$$2y$$05$$/SVcW3.dRcqFP61JCNgj9.L0BnTre7OnOL3E3dSHIUX0uKLp5aR/e'"

volumes:
  data-volume:
