version: "3.0"
networks:
  dgraph:

services:

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - dgraph


  zero:
    build:
      context: .
      dockerfile: Dockerfile

    image: chimpwizard/dgraph:latest
    #image: dgraph/dgraph:latest
    # volumes:
    #   - data-volume:/dgraph
    # port:
    #   - 5080:5080
    #   - 6080:6080 
    environment:
      - 'TASK_SLOT={{.Task.Slot}}'
    networks:
      - dgraph
        # aliases: 
        #   - zero
        #   - "{{.Service.Name}}.{{.Task.Slot}}"
    deploy:
      replicas: 3
    #command: --command zero -o -2000 --my=zero:5080 --replicas 3 
    #command: --command zero --my=zero:5080 --replicas 3 --peer zero:5080 --idx $$TASK_SLOT
    #command: --command zero --my=zero-$$TASK_SLOT:5080 --replicas 3 
    #command: dgraph zero --my=zero:5080 --replicas 3 
    #command: --command zero --my=zero:5080 --replicas 3 --idx $$TASK_SLOT --peer zero:5081 -o $$TASK_SLOT
    #command: --command zero --my=zero:5080 --replicas 3 --idx $$TASK_SLOT 
    #command: --command zero --my=zero:508$$TASK_SLOT --replicas 3 --idx $$TASK_SLOT  -o $$TASK_SLOT --peer zero:5081 --bindall --expose_trace --profile_mode block --block_rate 10 --logtostderr -v=2
    #command: --command zero --my zero:508$$TASK_SLOT --replicas 3 --idx $$TASK_SLOT  -o $$TASK_SLOT --peer zero:5081  -v 2
    command: --command zero --my $$HOSTNAME:508$$TASK_SLOT --replicas 3 --idx $$TASK_SLOT  -o $$TASK_SLOT --peer zero:5081  -v 2


  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: chimpwizard/dgraph:latest
    #image: dgraph/dgraph:latest
    # volumes:
    #   - data-volume:/dgraph
    # ports:
    #   - 8080:8080
    #   - 9080:9080
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 9080:9080
      - 9081:9081
      - 9082:9082
      - 9083:9083
    environment:
      - 'SOMENAME1={{.Service.ID}}'
      - 'SOMENAME2={{.Service.Name}}'
      - 'SOMENAME3={{.Service.Labels}}'
      - 'SOMENAME4={{.Node.ID}}'
      - 'SOMENAME5={{.Task.ID}}'
      - 'SOMENAME6={{.Task.Name}}'
      - 'TASK_SLOT={{.Task.Slot}}'
    networks:
      - dgraph
    deploy:
      replicas: 3
    #command: --command server --my=$$HOSTNAME:7080 --lru_mb=2048 --zero=zero:5080
    #command: dgraph server --my=$$HOSTNAME:7080 --lru_mb=2048 --zero=zero:5080
    #command: --command server --my=server:708$$TASK_SLOT --lru_mb=2048 --zero=zero:5081 -o $$TASK_SLOT --expose_trace  --trace 1.0 --profile_mode block --block_rate 10 --logtostderr -v=2
    #command: --command server --my server:708$$TASK_SLOT --lru_mb 2048 --zero zero:5081 -o $$TASK_SLOT  -v 2
    command: --command server --my $$HOSTNAME:7080 --lru_mb 2048 --zero zero:5081  -v 2

  ratel:
    image: dgraph/dgraph:latest
    # volumes:
    #   - /tmp/data:/dgraph
    ports:
      - 8000:8000
    networks:
      - dgraph
    command: dgraph-ratel

  console:
      image: portainer/portainer
      volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
      ports:
          - '9000:9000'
      networks:
          - dgraph
      command: "-H tcp://172.10.10.20:4243 --admin-password '$$2y$$05$$/SVcW3.dRcqFP61JCNgj9.L0BnTre7OnOL3E3dSHIUX0uKLp5aR/e'"

volumes:
  data-volume:
